### ISSUE TITLE
sourcelist security out of date

### ISSUE THREAD

**Issue by st0nec0ld** [heisath/wdmc2-kernel#10]
apt-get update shows error. the deb for security update is outdated.

https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#security-archive

this works
deb http://httpredir.debian.org/debian-security/ bullseye-security main contrib non-free
deb-src http://httpredir.debian.org/debian-security/ bullseye-security main contrib non-free

httpredir works, but also outdated https://wiki.debian.org/DebianGeoMirror

**Comment by Heisath** [comment]
Thanks for reporting, this has been fixed with commit fd189b97a49e695a40b13ef770b5335a1181c716.
