### ISSUE TITLE
No boot after reboot

### ISSUE THREAD

**Issue by st0nec0ld** [heisath/wdmc2-kernel#11]
After a reboot via cli, the system dont boot correctly. 

`root@wdnas:~# reboot -f`

LED flash red. 

![PXL_20220508_181541594](https://user-images.githubusercontent.com/21226229/167310361-a5d0f156-3490-47ec-a1e0-49ad497402e0.jpg)

Unplug/plug power is necessary.

**Comment by Heisath** [comment]
Hey, I can't reproduce this using bullseye and linux kernel 5.15. 
reboot works with and without force option.

Which versions are you using?  Also I noticed contrary to the other issue #12 both LEDs seem to be illuminated in your picture. Are you maybe using the (very old) fox version?

**Comment by Heisath** [comment]
It would also be great, if you could use the UART to get early console output. Maybe uboot tells you what is wrong.

**Comment by Heisath** [comment]
> Also I noticed contrary to the other issue #12 both LEDs seem to be illuminated in your picture. Are you maybe using the (very old) fox version?

Nvm this, just noticed in uboot both network LEDs are on.

Are you using a USB3.0 stick to boot?

**Comment by st0nec0ld** [comment]
Hey, thx for your quickly feedback. I made a bullseye build with 5.17 kernel and an usb3.0 stick.

After your feedback i try bullseye with 5.15 kernel and the usb3.0 stick, same fault. After that i try an old and slowly :( usb2.0 stick. Reboot works fine with 5.15 und 5.17.

Is my usb3.0 too fast (sandisk extreme usb3.0) or it is on the 3.0 standard?

Sorry. I dont know what "UART" is or how it works. I´m a newbie in linux :(

**Comment by Heisath** [comment]
This seems to be a general problem with usb3.0. Uboot seems to have problems with re-initialization...

UART is a serial port, very helpful when debugging low-level problems. https://github.com/Heisath/wdmc2-kernel/blob/master/docs/UART_Pins.txt
You can use USB2UART (ftdi) board with 3.3V signal level and attach it to the pins on wdmc, to get uboot output.
