### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by st0nec0ld** [heisath/wdmc2-kernel#15]
Sorry, me again :-)

Did you change anything?

I made a new build with with kernel 5.17 (usb boot) and i cant do an update, example:

root@wdusb:~# apt install ntp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libevent-core-2.1-7 libevent-pthreads-2.1-7 libopts25 sntp
Suggested packages:
  ntp-doc
The following packages will be REMOVED:
  systemd-timesyncd
The following NEW packages will be installed:
  libevent-core-2.1-7 libevent-pthreads-2.1-7 libopts25 ntp sntp
0 upgraded, 5 newly installed, 1 to remove and 0 not upgraded.
Need to get 1,140 kB of archives.
After this operation, 2,237 kB of additional disk space will be used.
W: Not using locking for read only lock file /var/lib/dpkg/lock-frontend
W: Not using locking for read only lock file /var/lib/dpkg/lock
W: chown to _apt:root of directory /var/cache/apt/archives/partial failed - SetupAPTPartialDirectory (30: Read-only file system)
W: chmod 0700 of directory /var/cache/apt/archives/partial failed - SetupAPTPartialDirectory (30: Read-only file system)
W: chown to _apt:root of directory /var/lib/apt/lists/auxfiles failed - SetupAPTPartialDirectory (30: Read-only file system)
W: chmod 0755 of directory /var/lib/apt/lists/auxfiles failed - SetupAPTPartialDirectory (30: Read-only file system)
W: Not using locking for read only lock file /var/cache/apt/archives/lock
Do you want to continue? [Y/n] y
Err:1 http://deb.debian.org/debian bullseye/main armhf libevent-core-2.1-7 armhf 2.1.12-stable-1
  Could not open file /var/cache/apt/archives/partial/libevent-core-2.1-7_2.1.12-stable-1_armhf.deb - open (30: Read-only file system) [IP: 151.101.14.132 80]
Err:2 http://deb.debian.org/debian bullseye/main armhf libevent-pthreads-2.1-7 armhf 2.1.12-stable-1
  Could not open file /var/cache/apt/archives/partial/libevent-pthreads-2.1-7_2.1.12-stable-1_armhf.deb - open (30: Read-only file system) [IP: 151.101.14.132 80]
Err:3 http://deb.debian.org/debian bullseye/main armhf libopts25 armhf 1:5.18.16-4
  Could not open file /var/cache/apt/archives/partial/libopts25_1%3a5.18.16-4_armhf.deb - open (30: Read-only file system) [IP: 151.101.14.132 80]
Err:4 http://deb.debian.org/debian bullseye/main armhf ntp armhf 1:4.2.8p15+dfsg-1
  Could not open file /var/cache/apt/archives/partial/ntp_1%3a4.2.8p15+dfsg-1_armhf.deb - open (30: Read-only file system) [IP: 151.101.14.132 80]
Err:5 http://deb.debian.org/debian bullseye/main armhf sntp armhf 1:4.2.8p15+dfsg-1
  Could not open file /var/cache/apt/archives/partial/sntp_1%3a4.2.8p15+dfsg-1_armhf.deb - open (30: Read-only file system) [IP: 151.101.14.132 80]
W: Download is performed unsandboxed as root as file '/var/cache/apt/archives/partial/libevent-core-2.1-7_2.1.12-stable-1_armhf.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/archives/partial/libevent-core-2.1-7_2.1.12-stable-1_armhf.deb - PrepareFiles (30: Read-only file system)
W: Problem unlinking the file /var/cache/apt/archives/partial/libevent-pthreads-2.1-7_2.1.12-stable-1_armhf.deb - PrepareFiles (30: Read-only file system)
W: Problem unlinking the file /var/cache/apt/archives/partial/libopts25_1%3a5.18.16-4_armhf.deb - PrepareFiles (30: Read-only file system)
W: Problem unlinking the file /var/cache/apt/archives/partial/ntp_1%3a4.2.8p15+dfsg-1_armhf.deb - PrepareFiles (30: Read-only file system)
W: Problem unlinking the file /var/cache/apt/archives/partial/sntp_1%3a4.2.8p15+dfsg-1_armhf.deb - PrepareFiles (30: Read-only file system)
E: Failed to fetch http://deb.debian.org/debian/pool/main/libe/libevent/libevent-core-2.1-7_2.1.12-stable-1_armhf.deb  Could not open file /var/cache/apt/archives/partial/libevent-core-2.1-7_2.1.12-stable-1_armhf.deb - open (30: Read-only file system) [IP: 151.101.14.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/libe/libevent/libevent-pthreads-2.1-7_2.1.12-stable-1_armhf.deb  Could not open file /var/cache/apt/archives/partial/libevent-pthreads-2.1-7_2.1.12-stable-1_armhf.deb - open (30: Read-only file system) [IP: 151.101.14.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/a/autogen/libopts25_5.18.16-4_armhf.deb  Could not open file /var/cache/apt/archives/partial/libopts25_1%3a5.18.16-4_armhf.deb - open (30: Read-only file system) [IP: 151.101.14.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/n/ntp/ntp_4.2.8p15%2bdfsg-1_armhf.deb  Could not open file /var/cache/apt/archives/partial/ntp_1%3a4.2.8p15+dfsg-1_armhf.deb - open (30: Read-only file system) [IP: 151.101.14.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/n/ntp/sntp_4.2.8p15%2bdfsg-1_armhf.deb  Could not open file /var/cache/apt/archives/partial/sntp_1%3a4.2.8p15+dfsg-1_armhf.deb - open (30: Read-only file system) [IP: 151.101.14.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

When i use an "old" 5.17 build, everything is okay.

*EDIT*
I try your build (https://github.com/Heisath/wdmc2-kernel/releases/tag/2022-05-30), same error.

**Comment by Heisath** [comment]
Are you sure this is not a device failure on your end?

**Comment by st0nec0ld** [comment]
i try two usb 2.0 sticks. both works with an "old" 5.17 kernel build i saved local. With new 5.17 kernel build both are read only. same install procedure with every build. i cant see an device failure.

i made some other research. something with fstab is wrong. you change and use "ln".
```
root@wdmycloud:~# ls -l /etc/fstab
lrwxrwxrwx 1 root root 52 Jun 15  2022 /etc/fstab -> /home/stone/wdmc2-kernel/output/rootfs/etc/fstab.usb
```
this is my local pfad and user from my laptop

checked your last release
```
root@wdmycloud:~# ls -l /etc/fstab
lrwxrwxrwx 1 root root 51 Jun 15  2022 /etc/fstab -> /home/user/wdmc2-kernel/output/rootfs/etc/fstab.usb
```
user is your linux user ;)

when i override the linked fstab with the fstab for usb, it works

i also tested to make another build, 3 times, same install procedure, 2 fails and 1 works.

hope you unterstand me, my english is bad

**Comment by Heisath** [comment]
Thanks for debugging this. Yeah the ln is not properly done. Can you fix it in build scripts? Otherwise I will in a few days, currently travelling...

Problem is here: https://github.com/Heisath/wdmc2-kernel/blob/c178ce2ae2522c74d056bda2152481d83ae93732/inc/rootfs.sh#L83-L85
The ln command needs to run in the chroot. See lines 90 following for reference.

ps. your english is fine. no worries.

**Comment by st0nec0ld** [comment]
sorry, i dont now how to do that in github. there is no hurry, enjoy your trip/vacation :)

**Comment by Heisath** [comment]
This should be fixed with https://github.com/Heisath/wdmc2-kernel/commit/1a37f49014f844afd090277b66c5644108a70b3c
I will test later and release a new build soon.
