### ISSUE TITLE
Custom kernel parameter

### ISSUE THREAD

**Issue by machsix** [heisath/wdmc2-kernel#25]
Thanks a lot for the great work! I wonder which file I should edit for custom kernel boot parameter. Specifically, I want to have `zswap.enabled=0` with a kernel built with ZSWAP

**Comment by Heisath** [comment]
Kernel boot parameters are passed by uboot. You could try changing it there. 

The other way would be to change the initramfs and override /proc/cmdline from there. 

Check https://github.com/Heisath/wdmc2-kernel/blob/master/build_initramfs.sh and https://wiki.archlinux.org/title/Kernel_parameters#Hijacking_cmdline
