### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Zeik0s** [heisath/wdmc2-kernel#4]
Sorry to bother you again, i noticed two things when i built 5.10.3:

- the package requirements are missing the _bc_ package, which wasn't installed on my current Debian Buster (but never stumbled over it before, so this package is also new to me.) So it may be good to add it.

- I only noticed that my kernel was not compiled when i tried to started it, because i didn't notice first that the default directory for gcc-arm-none-eabi is in /usr/bin instead of /opt.

**Comment by Heisath** [comment]
No bother :)

- To clarify, _bc_ is needed on the build host right?
- Yeah the directory of gcc's (installed via apt) goes to /usr/bin . But I thought it might be better to manual unpack the archives to /opt  ;  I will add some hint in the documentation & sourcecode

Both should have been fixed with 580a47f and c0959db

**Comment by Zeik0s** [comment]
Exactly, bc is needed on the host, where the build is made. 
Also the clarification in the build script helps. 

And i will continue to try building it, until now i haven't managed to get it running 😅

**Comment by Heisath** [comment]
Uff ok, if it helps I'm using Ubuntu Focal as a build host. You can also go back a few commits, 9b7f306, the build script had seperate kernel and rootfs scripts.

Also you can call `build.sh --kernelonly` to only test building the kernel. If it does not work you can post the output (if any), and I'll check it out.

**Comment by Zeik0s** [comment]
Yeah i will try focal next, maybe that's an issue due to older packages on debian. 
Just to be clear, for upgrading the Kernel, i need to copy uImage, uRamdisk and all linux kernel modules in /usr/lib/modules/$kernel-version ?

**Comment by Heisath** [comment]
To upgrade kernel you only need to copy uImage and modules. uRamdisk is only needed to load the file system and init. You don't have to upgrade it.
