### ISSUE TITLE
Wrong fstab

### ISSUE THREAD

**Issue by Zeik0s** [heisath/wdmc2-kernel#6]
I tried Version 1.4 of the rootfs, everything seems ok, apart from blocking connections on port 22. 
i've tried enabling the openssh-server, also with mounting the drive and chroot in there, and apparently the network stack is ok, because a dhcp lease is assigned and i can ping it, but an nmap shows that the port isn't open. I also removed nftables, because i thought this might block something, but it doesn't.

**Comment by Heisath** [comment]
Hey, 
thats interesting, thanks for reporting. I will try to reproduce this in the next days.

Are you running from usb or internal hdd?  Do you have access to the internal debug UART? I can provide picture, where it is located etc. will add this info to the repo shortly.

**Comment by Zeik0s** [comment]
Running from internal HDD.

I opened the case before, so i have physical access to the UART Pins, but have almost no experience with it. I think i have the necessary tools to get a UART connection working (soldering iron, cables, arduino repurposed as UART to USB converter), but feared doing that, also because i'm not sure if my arduino provides the right voltage for example 😅

14.05.2021 19:35:22 Jannis ***@***.***>:

**Comment by Heisath** [comment]
Internal voltage is 3.3V, UART pinout is here: https://github.com/heisath/wdmc2-kernel/blob/master/docs/UART_Pins.txt
(Arduino is possible, if it is 3.3V. Otherwise I'd suggest grabbing some switchable UART-USB converter. Or use 5V Arduino with some resistor or diodes as droppers...)

I did a quick check on my main WD, and it seems like there is indeed some iptables driver problem in the newer kernels (not sure if starting at 5.9 or 5.10), for me ssh works, but I cannot configure iptables (operation not supported). 

I'll have to go back to a kernel with working iptables and then bisect from there.

**Comment by Heisath** [comment]
@Zeik0s just in case it is not a iptables problem, you could also try to build (or mount the rootfs and comment) the ethtool line in /etc/network/interfaces:
https://github.com/heisath/wdmc2-kernel/blob/849220b0d5760ec068bb548cc48147ab1b739351/tweaks/interfaces.sh#L21

This ethtool optimization has caused problems in the past...

**Comment by Zeik0s** [comment]
Alright, will try that later.
My yesterday built version showed the same behaviour.

**Comment by Zeik0s** [comment]
the ethtool line is overwritten by the dhcpcd daemon, so that's not the case.

**Comment by Heisath** [comment]
Regarding my iptables thoughts above, can disregard that. While the new iptables (nf_tables) does not work (supposedly there's some module / driver missing), iptables_legacy works well. 

--> Error must be somewhere else. What kernel and debian are you using? In the first post you said V1.4 (buster+lk5.10), I will try this now.  Otherwise we need more information, as I did not have  a problem ssh'ing in...

**Comment by Heisath** [comment]
Tried by using V1.4 from this repo (just downloaded the rootfs tar, unzipped to usb and put boot on seperate fat partition). Boots and ssh works w/o problem.

Attached dmesg and syslog below:
DMESG: https://pastebin.com/LnkEDVhV
syslog: https://pastebin.com/a0eC31FJ

EDIT: One more tip/question, have you tried booting with the ethernet cable already plugged in? I remember there were some struggles with the interface not going completely up, when the cable gets connected later/not upon boot.

**Comment by Zeik0s** [comment]
ok, interesting. 

It boots from the usb, and allows ssh, but at the moment i'm not sure, which system is currently running. Because i downloaded and extracted your 1.4 Release with LK 5.10., but `uname -a` shows 5.8.0 #1 SMP Sat May 15 15:03:07 CEST 2021 where i tried version 5.8. 
Or did you change the buster-rootfs for the 1.4 release in the meantime?

**Comment by Zeik0s** [comment]
well, i think what i didn't get until now is to change the fstab, because i think with the predefined one it never booted into the actual system and did something else. (like a rescue mode or something like that, i don't know the features of u-boot) 

I needed to change it to my layout, which is like the one AllesterFox had on his box, with 

- sda1 => swap
- sda2 => data
- sda3 => root

Sorry for taking up your time. Time for me to get a serial usb adapter.

**Comment by Heisath** [comment]
No worries. 

Yeah the default rootfs and fstab gets build for usage with usb stick. So FAT (/dev/sdb1) as boot and EXT4 (/dev/sdb2) as root. 
The initramfs is checking possible locations one after another, https://github.com/heisath/wdmc2-kernel/blob/a30eee717ab3f42ec9be158a1e6b4a3dc0b4af8a/build_initramfs.sh#L84-L113

But the fstab is only premade for usb https://github.com/heisath/wdmc2-kernel/blob/master/tweaks/fstab.sh 

Reason for the need of 3 partitions if booting from internal hdd is that the uboot on the box only checks for /dev/sdb1 and /dev/sda3... I am not confident in updating the uboot on internal flash.

Personally I only use boot & root on usb stick, as this allows the harddrive to shutdown/sleep if unused for longer periods. Also swap on the hdd is not really neccessary, if you're using the zram tweak (and not doing very RAM intensive work): https://github.com/heisath/wdmc2-kernel/blob/master/tweaks/zram.sh

IMHO it would be great to have the buildscript more customisable via UI, so user gets asked for kernel version, os version, tweaks to apply, stuff like that. But I don't have the neccessary time right now...

Regarding l5.8 it is only included in release 1.2 but maybe you upgraded without changing your files in /boot ? I'd also strongly suggest to mainly use lk5.10 or 5.6 as these have the most stable & tested system.
